/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ActivityIndexRouteImport } from './routes/activity.index'
import { Route as ActivityTypeRouteImport } from './routes/activity.$type'
import { Route as ActivityNewRouteImport } from './routes/activity.new'
import { Route as HostVerifyRouteImport } from './routes/host.verify'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfilePasswordRouteImport } from './routes/profile.password'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsAboutRouteImport } from './routes/settings.about'
import { Route as SettingsFounderRouteImport } from './routes/settings.founder'
import { Route as SettingsHelpRouteImport } from './routes/settings.help'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsPrivacyRouteImport } from './routes/settings.privacy'
import { Route as SettingsTermsRouteImport } from './routes/settings.terms'
import { Route as ActivityIdNotificationsRouteImport } from './routes/activity.$id.notifications'
import { Route as ActivityManageIdRouteImport } from './routes/activity.manage.$id'
import { Route as ActivityViewIdRouteImport } from './routes/activity.view.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityTypeRoute = ActivityTypeRouteImport.update({
  id: '/activity/$type',
  path: '/activity/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityNewRoute = ActivityNewRouteImport.update({
  id: '/activity/new',
  path: '/activity/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HostVerifyRoute = HostVerifyRouteImport.update({
  id: '/host/verify',
  path: '/host/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePasswordRoute = ProfilePasswordRouteImport.update({
  id: '/profile/password',
  path: '/profile/password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/settings/about',
  path: '/settings/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsFounderRoute = SettingsFounderRouteImport.update({
  id: '/settings/founder',
  path: '/settings/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHelpRoute = SettingsHelpRouteImport.update({
  id: '/settings/help',
  path: '/settings/help',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/settings/notifications',
  path: '/settings/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTermsRoute = SettingsTermsRouteImport.update({
  id: '/settings/terms',
  path: '/settings/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIdNotificationsRoute = ActivityIdNotificationsRouteImport.update({
  id: '/activity/$id/notifications',
  path: '/activity/$id/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityManageIdRoute = ActivityManageIdRouteImport.update({
  id: '/activity/manage/$id',
  path: '/activity/manage/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityViewIdRoute = ActivityViewIdRouteImport.update({
  id: '/activity/view/$id',
  path: '/activity/view/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/activity/$type': typeof ActivityTypeRoute
  '/activity/new': typeof ActivityNewRoute
  '/host/verify': typeof HostVerifyRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/password': typeof ProfilePasswordRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/founder': typeof SettingsFounderRoute
  '/settings/help': typeof SettingsHelpRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/terms': typeof SettingsTermsRoute
  '/activity/': typeof ActivityIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/activity/$id/notifications': typeof ActivityIdNotificationsRoute
  '/activity/manage/$id': typeof ActivityManageIdRoute
  '/activity/view/$id': typeof ActivityViewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/activity/$type': typeof ActivityTypeRoute
  '/activity/new': typeof ActivityNewRoute
  '/host/verify': typeof HostVerifyRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/password': typeof ProfilePasswordRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/founder': typeof SettingsFounderRoute
  '/settings/help': typeof SettingsHelpRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/terms': typeof SettingsTermsRoute
  '/activity': typeof ActivityIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/activity/$id/notifications': typeof ActivityIdNotificationsRoute
  '/activity/manage/$id': typeof ActivityManageIdRoute
  '/activity/view/$id': typeof ActivityViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/activity/$type': typeof ActivityTypeRoute
  '/activity/new': typeof ActivityNewRoute
  '/host/verify': typeof HostVerifyRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/password': typeof ProfilePasswordRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/founder': typeof SettingsFounderRoute
  '/settings/help': typeof SettingsHelpRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/terms': typeof SettingsTermsRoute
  '/activity/': typeof ActivityIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/activity/$id/notifications': typeof ActivityIdNotificationsRoute
  '/activity/manage/$id': typeof ActivityManageIdRoute
  '/activity/view/$id': typeof ActivityViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/activity/$type'
    | '/activity/new'
    | '/host/verify'
    | '/profile/edit'
    | '/profile/password'
    | '/settings/about'
    | '/settings/founder'
    | '/settings/help'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/terms'
    | '/activity/'
    | '/profile/'
    | '/settings/'
    | '/activity/$id/notifications'
    | '/activity/manage/$id'
    | '/activity/view/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/activity/$type'
    | '/activity/new'
    | '/host/verify'
    | '/profile/edit'
    | '/profile/password'
    | '/settings/about'
    | '/settings/founder'
    | '/settings/help'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/terms'
    | '/activity'
    | '/profile'
    | '/settings'
    | '/activity/$id/notifications'
    | '/activity/manage/$id'
    | '/activity/view/$id'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/activity/$type'
    | '/activity/new'
    | '/host/verify'
    | '/profile/edit'
    | '/profile/password'
    | '/settings/about'
    | '/settings/founder'
    | '/settings/help'
    | '/settings/notifications'
    | '/settings/privacy'
    | '/settings/terms'
    | '/activity/'
    | '/profile/'
    | '/settings/'
    | '/activity/$id/notifications'
    | '/activity/manage/$id'
    | '/activity/view/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  ActivityTypeRoute: typeof ActivityTypeRoute
  ActivityNewRoute: typeof ActivityNewRoute
  HostVerifyRoute: typeof HostVerifyRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfilePasswordRoute: typeof ProfilePasswordRoute
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsFounderRoute: typeof SettingsFounderRoute
  SettingsHelpRoute: typeof SettingsHelpRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsTermsRoute: typeof SettingsTermsRoute
  ActivityIndexRoute: typeof ActivityIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ActivityIdNotificationsRoute: typeof ActivityIdNotificationsRoute
  ActivityManageIdRoute: typeof ActivityManageIdRoute
  ActivityViewIdRoute: typeof ActivityViewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/': {
      id: '/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/$type': {
      id: '/activity/$type'
      path: '/activity/$type'
      fullPath: '/activity/$type'
      preLoaderRoute: typeof ActivityTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/new': {
      id: '/activity/new'
      path: '/activity/new'
      fullPath: '/activity/new'
      preLoaderRoute: typeof ActivityNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/verify': {
      id: '/host/verify'
      path: '/host/verify'
      fullPath: '/host/verify'
      preLoaderRoute: typeof HostVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/password': {
      id: '/profile/password'
      path: '/profile/password'
      fullPath: '/profile/password'
      preLoaderRoute: typeof ProfilePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/settings/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/founder': {
      id: '/settings/founder'
      path: '/settings/founder'
      fullPath: '/settings/founder'
      preLoaderRoute: typeof SettingsFounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/help': {
      id: '/settings/help'
      path: '/settings/help'
      fullPath: '/settings/help'
      preLoaderRoute: typeof SettingsHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/terms': {
      id: '/settings/terms'
      path: '/settings/terms'
      fullPath: '/settings/terms'
      preLoaderRoute: typeof SettingsTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/$id/notifications': {
      id: '/activity/$id/notifications'
      path: '/activity/$id/notifications'
      fullPath: '/activity/$id/notifications'
      preLoaderRoute: typeof ActivityIdNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/manage/$id': {
      id: '/activity/manage/$id'
      path: '/activity/manage/$id'
      fullPath: '/activity/manage/$id'
      preLoaderRoute: typeof ActivityManageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/view/$id': {
      id: '/activity/view/$id'
      path: '/activity/view/$id'
      fullPath: '/activity/view/$id'
      preLoaderRoute: typeof ActivityViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  ActivityTypeRoute: ActivityTypeRoute,
  ActivityNewRoute: ActivityNewRoute,
  HostVerifyRoute: HostVerifyRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfilePasswordRoute: ProfilePasswordRoute,
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsFounderRoute: SettingsFounderRoute,
  SettingsHelpRoute: SettingsHelpRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsTermsRoute: SettingsTermsRoute,
  ActivityIndexRoute: ActivityIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ActivityIdNotificationsRoute: ActivityIdNotificationsRoute,
  ActivityManageIdRoute: ActivityManageIdRoute,
  ActivityViewIdRoute: ActivityViewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
